garage_vparrot/garage/urls.py
from django.urls import path

from . import views

app_name = "garage"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('vehicles/', views.VehiclesListView.as_view(), name='vehicles'),
    path('api/get/vehicles', views.VehiclesJsonResponse.as_view(), name='vehicles-json'),
    path('vehicles/<int:pk>/', views.VehicleView.as_view(), name='vehicle-detail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('legal-notice/', views.LegalNoticeView.as_view(), name='legal-notice'),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
]

garage_vparrot/garage_vparrot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('garage.urls')),
]

if settings.DEBUG:
    urlpatterns += [
       path('__debug__/', include(debug_toolbar.urls)),
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

garage_vparrot/garage/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.utils import timezone
from django.core import validators


class Garage(models.Model):
    name = models.CharField("nom", max_length=50)
    address = models.CharField("adresse", max_length=255)
    postal_code = models.CharField("code postal", max_length=10)
    city = models.CharField("ville", max_length=80)
    phone_number = models.CharField(
        "numéro de téléphone",
        max_length=20,
        validators=[
            validators.RegexValidator(
                regex=r"^0[1-9](\d{8})$",
                message="Entrez un numéro de téléphone français valide, ex: 0123456789.")
        ]
    )
    contact_email = models.CharField(
        "email de contact",
        max_length=254,
        validators=[
            validators.EmailValidator(message="L'adresse email est invalide.")
        ]
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "garage"


class OpeningTime(models.Model):
    class Day(models.TextChoices):
        MONDAY = "Lun.", "Lundi"
        TUESDAY = "Mar.", "Mardi"
        WEDNESDAY = "Mer.", "Mercredi"
        THURSDAY = "Jeu.", "Jeudi"
        FRIDAY = "Ven.", "Vendredi"
        SATURDAY = "Sam.", "Samedi"
        SUNDAY = "Dim.", "Dimanche"

    day = models.CharField(
        "jour de la semaine",
        max_length=10,
        choices=Day.choices,
    )
    opening_hours = models.CharField("horaires d'ouverture", max_length=80)
    garage = models.ForeignKey(
        Garage,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="garage",
    )

    def __str__(self) -> str:
        return self.day

    class Meta:
        verbose_name = "horaire"


class ServiceType(models.Model):
    name = models.CharField("nom", max_length=50)
    image = models.ImageField("image", upload_to="uploads/%Y/%m/")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "type de service"
        verbose_name_plural = "types de service"


class Service(models.Model):
    name = models.CharField("nom", max_length=80)
    type = models.ForeignKey(
        ServiceType,
        on_delete=models.PROTECT,
        related_name="service_name"
    )
    garage = models.ForeignKey(
        Garage,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="garage",
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "service"


class Vehicle(models.Model):
    name = models.CharField("nom", max_length=24)
    brand = models.CharField("marque", max_length=30)
    model = models.CharField("modèle", max_length=30)
    energy = models.CharField("énergie", max_length=30)
    gearbox = models.CharField("boîte de vitesse", max_length=30)
    color = models.CharField("couleur", max_length=30)
    seats = models.PositiveIntegerField("nombre de places")
    critair = models.PositiveIntegerField("crit'air")
    power = models.PositiveIntegerField("puissance (cv)")
    price = models.PositiveIntegerField("prix")
    year = models.PositiveSmallIntegerField("année")
    km = models.PositiveIntegerField("kilométrage")
    garage = models.ForeignKey(
        Garage,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="garage",
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "véhicule"


class VehiclePicture(models.Model):
    vehicle = models.ForeignKey(
        Vehicle,
        on_delete=models.CASCADE,
        related_name="pictures",
    )
    picture = models.ImageField("photos", upload_to="uploads/%Y/%m/")

    def __str__(self) -> str:
        return self.picture.name

    class Meta:
        verbose_name = "photo d'un véhicule"
        verbose_name_plural = "photos des véhicules"


class CustomerReview(models.Model):
    name = models.CharField("nom", max_length=50)
    message = models.TextField("message", max_length=2000)
    rating = models.PositiveSmallIntegerField(
        "note",
        validators=[
            validators.MaxValueValidator(5, message="La note maximale est 5 étoiles."),
            validators.MinValueValidator(0, message="La note minimale est 0 étoile."),
        ]
    )
    valid = models.BooleanField("valide", null=True)
    date = models.DateTimeField("date de réception", auto_now_add=True)

    validator = models.ForeignKey(
        auth_models.User,
        on_delete=models.PROTECT,
        verbose_name="modérateur",
        null=True,
        blank=True,
    )
    # verification_date = models.DateTimeField("date de modération", auto_now=True)
    garage = models.ForeignKey(
        Garage,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="garage",
    )

    def __str__(self) -> str:
        local_date = timezone.localtime(self.date)
        return (
            f"Témoignage de {self.name} reçu le "
            f"{local_date.strftime('%d/%m/%Y, %H:%M:%S')}"
        )

    def list_to_display_stars(self) -> list:
        list_stars = []
        for i in range(5):
            if self.rating > i:
                list_stars.append("star")
            else:
                list_stars.append("empty")
        return list_stars

    class Meta:
        verbose_name = "témoignage client"
        verbose_name_plural = "témoignages client"


class CustomerMessage(models.Model):
    first_name = models.CharField("prénom", max_length=80)
    last_name = models.CharField("nom", max_length=80)
    email = models.EmailField(
        "email",
        max_length=254,
        validators=[
            validators.EmailValidator(message="Entrez une adresse email valide.")
        ]
    )
    phone_number = models.CharField(
        "numéro de téléphone",
        max_length=20,
        validators=[
            validators.RegexValidator(
                regex=r"^0[1-9](\d{8})$",
                message="Entrez un numéro de téléphone français valide, ex: 0123456789.")
        ]
    )
    subject = models.CharField("sujet", max_length=255, blank=True, null=True)
    message = models.TextField("message", max_length=5000)
    date = models.DateTimeField("date de réception", auto_now_add=True)
    garage = models.ForeignKey(
        Garage,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="garage",
    )

    def __str__(self) -> str:
        local_date = timezone.localtime(self.date)
        return (
            f"Message de {self.first_name} {self.last_name} reçu le "
            f"{local_date.strftime('%d/%m/%Y, %H:%M:%S')}"
        )

    class Meta:
        verbose_name = "message client"
        verbose_name_plural = "messages client"

garage_vparrot/garage/views.py
from math import floor, ceil
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib import messages
from django.forms.models import model_to_dict
from django.views.generic import View, TemplateView, FormView, ListView, DetailView
from .modelforms import ContactForm, VehicleContactForm, ReviewForm
from .models import OpeningTime, Service, Vehicle, VehiclePicture, CustomerReview


class IndexView(View):
    @staticmethod
    def get(request, *args, **kwargs):
        view = IndexTemplateView.as_view()
        return view(request, *args, **kwargs)

    @staticmethod
    def post(request, *args, **kwargs):
        view = IndexReviewFormView.as_view()
        return view(request, *args, **kwargs)


class IndexTemplateView(TemplateView):
    template_name = 'garage/index.html'
    review_form_success_msg_title = "Témoignage reçu"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["services"] = Service.objects.all()
        context["reviews"] = CustomerReview.objects.filter(valid=True).order_by("-date")[:3]
        context["opening_time"] = OpeningTime.objects.all()
        context["review_form"] = ReviewForm()
        context["messages_title"] = self.review_form_success_msg_title
        return context


class IndexReviewFormView(FormView):
    template_name = 'garage/index.html'
    form_class = ReviewForm
    success_url = '/'
    success_message = "Bonjour {name}, merci pour votre témoignage !"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, self.success_message.format(name=form.cleaned_data.get("name")))
        return super().form_valid(form)


class VehiclesListView(ListView):
    template_name = 'garage/vehicles.html'
    model = Vehicle
    context_object_name = 'vehicles'
    paginate_by = 6
    ordering = 'km'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["opening_time"] = OpeningTime.objects.all()

        # SET FILTER VEHICLE PRICE MIN AND MAX
        vehicles_sorted_by_price = Vehicle.objects.order_by('price')
        filter_price_step = 1000
        context["filter_price_min"] = floor(
            vehicles_sorted_by_price.first().price / filter_price_step) * filter_price_step
        context["filter_price_max"] = ceil(
            vehicles_sorted_by_price.last().price / filter_price_step) * filter_price_step
        context["filter_price_step"] = filter_price_step
        # SET FILTER VEHICLE YEAR MIN AND MAX
        vehicles_sorted_by_year = Vehicle.objects.order_by('year')
        filter_year_step = 1
        context["filter_year_min"] = floor(vehicles_sorted_by_year.first().year / filter_year_step) * filter_year_step
        context["filter_year_max"] = ceil(vehicles_sorted_by_year.last().year / filter_year_step) * filter_year_step
        context["filter_year_step"] = filter_year_step
        # SET FILTER VEHICLE KM MIN AND MAX
        vehicles_sorted_by_km = Vehicle.objects.order_by('km')
        filter_km_step = 1000
        context["filter_km_min"] = floor(vehicles_sorted_by_km.first().km / filter_km_step) * filter_km_step
        context["filter_km_max"] = ceil(vehicles_sorted_by_km.last().km / filter_km_step) * filter_km_step
        context["filter_km_step"] = filter_km_step

        return context


class VehiclesJsonResponse(View):
    default_page = 1
    paginate_by = 6
    ordering = 'price'

    def get(self, request, *args, **kwargs):
        # GET REQUEST PARAMS
        page = self.request.GET.get('page')
        search = self.request.GET.get('search')
        sort_by = self.request.GET.get('sort_by')
        limit = self.request.GET.get('limit')
        price_min = self.request.GET.get('price_min')
        price_max = self.request.GET.get('price_max')
        year_min = self.request.GET.get('year_min')
        year_max = self.request.GET.get('year_max')
        km_min = self.request.GET.get('km_min')
        km_max = self.request.GET.get('km_max')

        # GET ALL VEHICLES
        vehicles = Vehicle.objects.all()

        # SEARCH VEHICLES
        if search:
            vehicles = vehicles.filter(name__icontains=search)
        # FILTERING VEHICLES
        if price_min:
            vehicles = vehicles.filter(price__gte=price_min)
        if price_max:
            vehicles = vehicles.filter(price__lte=price_max)
        if year_min:
            vehicles = vehicles.filter(year__gte=year_min)
        if year_max:
            vehicles = vehicles.filter(year__lte=year_max)
        if km_min:
            vehicles = vehicles.filter(km__gte=km_min)
        if km_max:
            vehicles = vehicles.filter(km__lte=km_max)

        # SORTING VEHICLES
        if sort_by:
            vehicles = vehicles.order_by(sort_by)
        else:
            vehicles = vehicles.order_by(self.ordering)

        # PAGINATION OF VEHICLES
        if page:
            num_page = page
        else:
            num_page = self.default_page

        # PAGINATE BY
        if limit:
            vehicle_per_page = limit
        else:
            vehicle_per_page = self.paginate_by

        # PAGINATION
        paginator = Paginator(vehicles, vehicle_per_page)
        page_obj = paginator.get_page(num_page)

        # CREATE DICT OF VEHICLES
        vehicle_dict = {}
        count = 0
        for vehicle in page_obj:
            count += 1
            vehicle_dict[count] = model_to_dict(vehicle)
            pictures = VehiclePicture.objects.filter(vehicle=vehicle)
            vehicle_dict[count]['pictures'] = [picture.picture.url for picture in pictures]

        # CREATE RESPONSE DICT
        response = {
            "vehicles": vehicle_dict,
            "pagination": {
                "page": num_page,
                "has_previous": page_obj.has_previous(),
                "has_next": page_obj.has_next(),
                "paginate_by": paginator.per_page,
                "num_pages": paginator.num_pages
            }
        }
        return JsonResponse(response)


class VehicleView(View):
    @staticmethod
    def get(request, *args, **kwargs):
        view = VehicleDetailView.as_view()
        return view(request, *args, **kwargs)

    @staticmethod
    def post(request, *args, **kwargs):
        view = VehicleContactFormView.as_view()
        return view(request, *args, **kwargs)


class VehicleDetailView(DetailView):
    template_name = 'garage/vehicle-detail.html'
    model = Vehicle
    context_object_name = 'vehicle'
    contact_form_success_msg_title = "Demande de contact reçu"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["opening_time"] = OpeningTime.objects.all()
        context["contact_form"] = VehicleContactForm()
        context["messages_title"] = self.contact_form_success_msg_title

        return context


class VehicleContactFormView(FormView):
    template_name = 'garage/vehicle-detail.html'
    model = Vehicle
    form_class = VehicleContactForm
    success_message = ("Bonjour {first_name}, merci de nous avoir contactés à propos de ce véhicule. Nous revenons "
                       "vers vous au plus vite.")

    def form_valid(self, form):
        form.save()
        form.send_email()
        messages.success(self.request, self.success_message.format(first_name=form.cleaned_data.get("first_name")))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('garage:vehicle-detail', kwargs={'pk': self.kwargs['pk']})


class ContactView(FormView):
    template_name = 'garage/contact.html'
    form_class = ContactForm
    success_url = '/contact/'
    contact_form_success_msg_title = "Demande de contact reçu"
    success_message = "Bonjour {first_name}, merci de nous avoir contactés. Nous revenons vers vous au plus vite."

    def form_valid(self, form):
        form.save()
        form.send_email()
        messages.success(self.request, self.success_message.format(first_name=form.cleaned_data.get("first_name")))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["opening_time"] = OpeningTime.objects.all()
        context["messages_title"] = self.contact_form_success_msg_title
        return context


class LegalNoticeView(TemplateView):
    template_name = 'garage/legal-notice.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["opening_time"] = OpeningTime.objects.all()
        return context


class PrivacyPolicyView(TemplateView):
    template_name = 'garage/privacy-policy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["opening_time"] = OpeningTime.objects.all()
        return context

garage_vparrot/garage/templates/garage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr" class="scroll-smooth">
<head>
    <!-- META-->
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="robots" content="noindex, nofollow"/>
    {% block meta %}{% endblock %}

    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'garage/images/favicons/apple-touch-icon.png' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'garage/images/favicons/favicon-32x32.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'garage/images/favicons/favicon-16x16.png' %}"/>
    <link rel="manifest" href="{% static 'garage/images/favicons/site.webmanifest' %}"/>
    <link rel="mask-icon" href="{% static 'garage/images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5"/>
    <link rel="shortcut icon" href="{% static 'garage/images/favicons/favicon.ico' %}"/>
    <meta name="msapplication-TileColor" content="#2d89ef"/>
    <meta name="msapplication-config" content="{% static 'garage/images/favicons/browserconfig.xml' %}"/>
    <meta name="theme-color" content="#ffffff"/>

    <!-- GOOGLE FONTS : ROKKITT, RASA, NOBILE -->
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link href="https://fonts.googleapis.com/css2?family=Nobile:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&family=Rasa:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Rokkitt:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"/>

    <!-- TAILWIND CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'garage/style/output.css' %}"/>

    <!-- LEAFLET CSS & JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin="" defer></script>

    <!-- SCRIPTS JS -->
    <script src="{% static 'garage/javascript/base.js' %}" defer></script>
    {% block scripts %}{% endblock %}

    <!-- TITLE & DESCRIPTION -->
    <title>{% block title %}Garage V.Parrot à Toulouse{% endblock %}</title>
    <meta name="description" content="{% block meta-description %}{% endblock %}"/>
</head>

<!-- BODY -->
<body class="preload font-nobile bg-whiteTeal">

<!-- HEADER -->
{% include 'garage/header.html' %}

<!-- MAIN -->
<main>
    {% block main %}{% endblock %}
</main>

<!-- FOOTER -->
{% include 'garage/footer.html' %}

</body>
</html>

garage_vparrot/garage/templates/garage/footer.html
{% load static %}

<footer>
    <section id="opening-time" class="bg-celestialBlue">
        <div class="flex flex-row justify-evenly items-center lg:container mx-auto">
            <div class="flex flex-col flex-nowrap justify-center items-center md:items-start px-4 sm:px-6 md:px-4 py-10 sm:py-12">
                <h2 class="font-rasa text-whiteTeal text-xl uppercase mb-4 sm:mb-6">
                    Horaires d'ouverture
                </h2>
                <div class="grid grid-cols-5 grid-rows-7 gap-y-2 text-whiteTeal">
                    {% for opening in opening_time %}
                        <div>{{ opening.day }}</div>
                        <div class="col-span-4">: {{ opening.opening_hours }}</div>
                    {% endfor %}
                </div>
            </div>
            <div id="leaflet-map"
                 class="hidden md:block md:h-56 md:w-80 lg:h-64 lg:w-96 xl:h-72 xl:w-128 px-4 z-0 rounded-sm"></div>
        </div>
    </section>

    <section id="address-infos" class="bg-onyx">
        <div class="flex flex-col md:flex-row flex-nowrap justify-center md:justify-evenly items-center text-center md:text-left px-4 sm:px-6 md:px-8 py-4 sm:py-6 text-whiteTeal md:container mx-auto">
            <h2 class="font-rasa text-xl uppercase mb-4 hidden">
                Adresse et informations
            </h2>
            <img class="w-48 h-auto" src="{% static 'garage/images/logos/Logo-black.webp' %}"
                 alt="Logo du Garage V.Parrot"/>
            <div class="w-12 md:hidden">
                <hr class="rounded">
            </div>
            <nav class="my-4 md:my-0 sm:mx-2 md:me-4 md:mx-6 md:me-8" aria-label="footer-nav">
                <ul>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:index' %}#about">Présentation</a>
                    </li>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:index' %}#services">Nos Services</a>
                    </li>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:index' %}#reviews">Témoignages</a>
                    </li>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:vehicles' %}">Véhicules d'occasion</a>
                    </li>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:index' %}#opening-time">Nos horaires</a>
                    </li>
                    <li class="mb-1">
                        <a class="transition hover:text-celestialBlue active:text-darkBlue"
                           href="{% url 'garage:contact' %}">Nous contacter</a>
                    </li>
                </ul>
            </nav>
            <div class="w-12 md:hidden">
                <hr class="rounded"/>
            </div>
            <div class="flex flex-col flex-nowrap md:mx-8">
                <div class="text-sm mt-4 md:mt-0 mb-4 leading-relaxed">
                    <p>Garage V.Parrot</p>
                    <p>
                        11 Rue Léon Jouhaux<br>
                        31500 Toulouse
                    </p>
                    <p>Tel. : <a href="tel:+33561234567">05 61 23 45 67</a></p>
                </div>
                <p class="flex flex-col flex-nowrap text-xs leading-normal">
                    <a class="transition hover:text-celestialBlue hover:underline active:text-darkBlue"
                       href="{% url 'garage:legal-notice' %}">Mentions légales</a>

                    <a class="transition hover:text-celestialBlue hover:underline active:text-darkBlue"
                       href="{% url 'garage:privacy-policy' %}">Politique de confidentialité des données</a>

                    Garage V.Parrot ©2023
                </p>
            </div>
        </div>
    </section>
</footer>

garage_vparrot/garage/templates/garage/header.html
{% load static %}

<header class="bg-onyx border-b border-celestialBlue">
    <nav class="flex flex-row flex-nowrap justify-between items-center h-16 xl:container mx-auto" aria-label="header-nav">
        <div>
            <a class="flex flex-row justify-center items-center ms-3 sm:ms-6 md:ms-8"
               href="{% url 'garage:index' %}">
                <img class="w-auto h-16" src="{% static 'garage/images/logos/Logo-icon-black.webp' %}"
                     alt="Logo du Garage V.Parrot"/>
                <span class="font-bold text-whiteTeal text-lg pt-1">V.Parrot</span>
            </a>
        </div>
        <ul class="lg:flex flex-row flex-nowrap hidden text-md uppercase me-8 pt-1">
            <li class="mx-3">
                <a class="text-whiteTeal transition hover:text-celestialBlue active:text-darkBlue"
                   href="{% url 'garage:index' %}">Accueil</a>
            </li>
            <li class="mx-3">
                <a class="text-whiteTeal transition hover:text-celestialBlue active:text-darkBlue"
                   href="{% url 'garage:index' %}#services">Services</a>
            </li>
            <li class="mx-3">
                <a class="text-whiteTeal transition hover:text-celestialBlue active:text-darkBlue"
                   href="{% url 'garage:vehicles' %}">Véhicules d'occasion</a>
            </li>
            <li class="mx-3">
                <a class="text-whiteTeal transition hover:text-celestialBlue active:text-darkBlue"
                   href="{% url 'garage:contact' %}">Contact</a>
            </li>
            <li class="mx-3 ps-6 border-s-2">
                <a class="text-whiteTeal transition hover:text-celestialBlue active:text-darkBlue"
                   href="{% url 'admin:login' %}">Connexion</a>
            </li>
        </ul>
        <button type="button" id="btn-mobile-menu" class="lg:hidden" aria-label="mobile-menu">
            <div class="flex flex-col flex-nowrap justify-center items-center p-2 me-3 sm:me-6 md:me-8">
                <div id="btn-mobile-menu-line1"
                     class="h-0.75 w-7 my-0.75 rounded bg-whiteTeal transition ease-in transform duration-300"></div>
                <div id="btn-mobile-menu-line2"
                     class="h-0.75 w-7 my-0.75 rounded bg-whiteTeal transition ease-in transform duration-300"></div>
                <div id="btn-mobile-menu-line3"
                     class="h-0.75 w-7 my-0.75 rounded bg-whiteTeal transition ease-in transform duration-300"></div>
            </div>
        </button>
    </nav>
    <div id="mobile-menu"
         class="flex flex-col flex-nowrap px-6 sm:px-8 md:px-12 bg-celestialBlue h-0 overflow-hidden transition-height duration-200 ease-in">
        <ul class="font-medium text-lg uppercase">
            <li class="mt-6 mb-1">
                <a href="{% url 'garage:index' %}"
                   class="text-whiteTeal transition hover:text-onyx active:text-darkBlue hover:underline hover:underline-offset-4 hover:decoration-1">Accueil</a>
            </li>
            <li class="mt-2 mb-1">
                <a href="{% url 'garage:index' %}#services"
                   class="text-whiteTeal transition hover:text-onyx active:text-darkBlue hover:underline hover:underline-offset-4 hover:decoration-1">Services</a>
            </li>
            <li class="mt-2 mb-1">
                <a href="{% url 'garage:vehicles' %}"
                   class="text-whiteTeal transition hover:text-onyx active:text-darkBlue hover:underline hover:underline-offset-4 hover:decoration-1">Véhicules
                    d'occasion</a>
            </li>
            <li class="mt-2 mb-1">
                <a href="{% url 'garage:contact' %}"
                   class="text-whiteTeal transition hover:text-onyx active:text-darkBlue hover:underline hover:underline-offset-4 hover:decoration-1">Contact</a
                ></li>
            <li class="mt-2 mb-1">
                <a href="{% url 'admin:login' %}"
                   class="text-whiteTeal transition hover:text-onyx active:text-darkBlue hover:underline hover:underline-offset-4 hover:decoration-1">Connexion</a>
            </li>
        </ul>
    </div>
</header>